---
# Só mude aqui!!!!
author: "Luiz Gustavo Alves Carvalho"
title: "Relatório de Aula Prática 01"
bibliography: referencias.bib
# A partir daqui nao faca alteracoes!!!!!
link-citations: true
csl: associacao-brasileira-de-normas-tecnicas-ipea.csl
subtitle: "<a href='https://bendeivide.github.io/courses/epaec/' target='_blank'>Estatística e Probabilidade</a> </br> <a href='https://bendeivide.github.io' target='_blank'>Prof. Ben Dêivide (DEFIM/CAP/UFSJ)</a>"
include-before-body: header.html
date: now
date-format: "DD/MM/YYYY, HH:mm"
lang: pt-BR
format:
  html:
    toc: true
    number-sections: true
    theme: bootstrap
    #css: styles.css
    code-fold: true
    code-tools: true
execute:
  echo: true
  warning: false
  message: false
---


## 📌 Introdução

A prática de lançamento de uma catapulta foi realizada como atividade experimental para a coleta de dados referentes a 22 lançamentos, com o objetivo de aplicar conceitos estatísticos, incluindo média, variância, desvio padrão, mediana e moda. Adicionalmente, buscou-se desenvolver habilidades de programação na linguagem R. Para isso, utilizou-se a biblioteca leem para a leitura e organização dos dados, bem como para a geração de gráficos, em conjunto com o LaTeX para a elaboração e formatação das expressões matemáticas.



## 🎯 Objetivos

### Objetivo geral
O experimento teve como objetivo aplicar variações no lançamento de projéteis de uma catapulta e coletar dados para utilizar técnicas de estatística e organizá-los em tabelas.

### Objetivos específicos

- Coletar dados experimentais  
- Construir gráficos  
- Interpretar resultados  

---

## 📚  Fundamentação Teórica

Conceitos principais de estatística:

- Média Aritmética
$$
\begin{matrix}
\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i \\[10pt]
\bar{x}: \text{Símbolo da média da amostra} \\
n: \text{Tamanho da amostra} \\
x_i: \text{Valor de cada dado}
\end{matrix}
$$


- Variância Amostral
$$
\begin{matrix}
s^2 = \frac{1}{n-1}\sum_{i=1}^{n}(x_i - \bar{x})^2 \\[10pt]
s^2: \text{Variância da amostra} \\
n-1: \text{Graus de liberdade} \\
(x_i - \bar{x}): \text{Desvio em relação à média}
\end{matrix}
$$

- Desvio padrão
$$
\begin{matrix}
s = \sqrt{\frac{1}{n-1}\sum_{i=1}^{n}(x_i - \bar{x})^2} \\[10pt]
s: \text{Desvio padrão da amostra} \\
\text{Indica a dispersão dos dados em relação à média}
\end{matrix}
$$

- Mediana
$$
\begin{matrix}
\text{Mediana} = \begin{cases} x_{\frac{n+1}{2}}, & \text{se } n \text{ ímpar} \\ \frac{x_{\frac{n}{2}} + x_{\frac{n}{2}+1}}{2}, & \text{se } n \text{ par} \end{cases} \\[10pt]
n: \text{Número total de elementos} \\
x: \text{Posição do valor no conjunto ordenado}
\end{matrix}
$$

- moda
$$
\begin{matrix}
\text{Moda} = x_k \text{ tal que } f(x_k) = \max(f(x_i)) \\[10pt]
f(x_k): \text{Frequência do valor } x_k \\
\max: \text{Valor que ocorre mais vezes}
\end{matrix}
$$

- Amplitude
$$
\begin{matrix}
A = x_{\max} - x_{\min} \\[10pt]
x_{\max}: \text{Valor máximo do conjunto} \\
x_{\min}: \text{Valor mínimo do conjunto}
\end{matrix}
$$

- Coeficiente de Variação
$$
\begin{matrix}
CV = \frac{s}{\bar{x}} \times 100\% \\[10pt]
s: \text{Desvio padrão} \\
\bar{x}: \text{Média aritmética} \\
100\%: \text{Expressa o resultado em porcentagem}
\end{matrix}
$$

- Erro padrão da Média
$$
\begin{matrix}
EPM = \frac{s}{\sqrt{n}} \\[10pt]
s: \text{Desvio padrão da amostra} \\
\sqrt{n}: \text{Raiz quadrada do tamanho da amostra}
\end{matrix}
$$

Conceitos principais Elasticidade:

- Lei de Hooke
$$
\begin{matrix}
F = kx \\[10pt]
F: \text{Força aplicada pelo elástico} \\
k: \text{Constante elástica (rigidez)} \\
x: \text{Deformação ou distensão do elástico}
\end{matrix}
$$
Permite calcular a força aplicada ao projétil no momento do lançamento. Quanto maior a força, maior será a aceleração e, consequentemente, o alcance.

- Degradação da constante elástica
$$
\begin{matrix}
k(n) = k_0 \cdot e^{-\alpha n} \\[10pt]
k(n): \text{Constante elástica após } n \text{ lançamentos} \\
k_0: \text{Constante elástica inicial} \\
\alpha: \text{Coeficiente de fadiga do material} \\
n: \text{Número de repetições (lançamentos)}
\end{matrix}
$$
Explica por que os lançamentos ficam mais fracos ao longo do tempo, mesmo usando a mesma deformação. É essencial para entender erros e variações nos resultados.


- Energia potencial elástica
$$
\begin{matrix}
E = \frac{1}{2} k x^2 \\[10pt]
E: \text{Energia acumulada no elástico} \\
k: \text{Constante elástica} \\
x: \text{Distância da deformação}
\end{matrix}
$$
Essa energia é convertida em movimento do projétil. Quanto maior a energia, maior tende a ser a velocidade inicial e o alcance da catapulta.

Conceitos Principais Termodinamica:

- Relação temperatura e constante elástica
$$
\begin{matrix}
k(T) = k_0 \cdot (1 - \beta \Delta T) \\[10pt]
k(T): \text{Constante elástica na temperatura atual} \\
\beta: \text{Coeficiente de sensibilidade térmica} \\
\Delta T: \text{Variação de temperatura} \\
\text{Explica a variação da força conforme o clima do laboratório}
\end{matrix}
$$
elástico é um material sensível ao calor,por isso é melhor levar em consideração que a constante elástica varia com a temperatura.
Temperaturas mais altas → elástico mais “mole” → menor k → menor força → menor alcance
Temperaturas mais baixas → elástico mais rígido → maior k → maior força (até certo limite)

- Para a elaboração das fórmulas matemáticas, foi utilizada uma playlist do youtube @latex

---

## ⚙️ Metodologia


 Para a coleta dos dados, utilizamos como superfície de apoio da catapulta uma mesa escolar, considerando possíveis desníveis e utilizando O- =Nível 2 , A+= Nível 3, B+= 90°, A-= Nível 4, como de variaveis constantes da configuração da catapulta . A catapulta estava firme na mesa, presa com grampos bem fixados. Foram realizadas 22 repetições, com medições em centímetros, com aproximação até os milímetros.

 O Nível O-:
Ponto de referência: é o apoio superior da catapulta, altera a trajetória do projétil.
 
 O Nível A+:
Tensão do elástico: observa-se a deformação do elástico, alterando a energia potencial elástica. Por ela, podemos prever se a distância percorrida vai ser maior ou menor que as anteriores.
 
 O Nível B+:
Alteração do ângulo de saída do projétil: quanto mais próximo do ângulo de 45°, mais próximo estaremos da sua distância horizontal máxima; e quanto mais próximo do ângulo de 90°, mais próximo estaremos da altura máxima.
 
 O Nível A-:
Tensão do elástico, mas com menor energia potencial elástica: ela influencia o oposto do nível A+, pois quanto menor a energia potencial, menor será a velocidade inicial e, consequentemente, menor será a distância total percorrida.


---

## 🔍 Resultados e Discussão

DADOS COLETADOS:
1-326;
2-294,8;
3-296,8;
4-294;
5-295,8;
6-298,5;
7-300,6;
8-285,1;
9-287,1;
10-292,3;
11-290,8;
12-287,9;
13-282,9;
14-285,3;
15-281,5;
16-278,4;
17-276,4;
18-281,7;
19-277,1;
20-285,3;
21-277,1;
22-281,8.

Analise desse dados nós mostra que a média (≈ 288,69) e a mediana (= 286,2) estão muito próximas, indicando que os resultados são bem distribuídos e não sofrem grande influência de valores extremos. Além disso, a presença de duas modas (277,1 e 285,3) indica que alguns valores se repetiram com mais frequência, provavelmente devido à repetição de condições semelhantes nos lançamentos da catapulta.

 O desvio padrão (≈ 7,77), considerado baixo em relação ao coeficiente de variação (≈ 3,69%), demonstra que há pouca dispersão nos dados, o que evidencia a consistência dos resultados ao longo das medições. Mesmo assim, existem alguns valores fora do padrão, como o lançamento 17 (276,4 cm) e o primeiro lançamento (326,0 cm), que se destacam dos demais.

 Em experimentos de lançamento de projéteis, é esperado haver variações por causa de fatores mecânicos e ambientais. Ainda assim, os resultados mostram boa repetibilidade, já que a maior parte das medidas se concentra próxima da média. Isso também é reforçado pelo coeficiente de variação (≈ 3,69%), que indica baixa variabilidade no conjunto de dados.
 
 As pequenas variações observadas podem ser explicadas por fatores como mudanças na tensão da catapulta, atrito ou desgaste do mecanismo, pequenas diferenças na posição do projétil e irregularidades na superfície de apoio, como uma mesa levemente desnivelada. Além disso, erros experimentais também podem ter influenciado os resultados, como imprecisões nas medições com régua ou fita métrica, arredondamentos na leitura das distâncias, variações na forma de acionar a catapulta, possível instabilidade do equipamento e até a influência da força elástica e da temperatura.
 
- A análise estatística foi baseada em @estatistica2024

### 📊  Análise de Dados

```{r}
library(leem)
dados1<- read.csv2("ap01.csv", skip = 1)
dist1<- c(dados1[[2]])
dist1 |>
  new_leem(variable = 2) |>
  tabfreq() |>
  hist()|>
  insert(type = "all", 
    lcol = c("black", "blue", "brown"),
    ptext = 0.08, larrow = 0.4) 
```
Os resultados apresentam uma distribuição com assimetria positiva, visto que moda<mediana<media. Essa característica indica uma concentração de lançamentos em distâncias menores, com a presença de valores mais elevados que deslocaram a média aritmética para a direita do centro da distribuição."

- Foi utilizada a biblioteca leem no R para criação dos gráficos @leem

## 🧠 Considerações finais

 O objetivo do experimento foi realizar variações no lançamento de projéteis com o uso de uma catapulta, coletar os dados e analisá-los por meio de técnicas de estatística descritiva, além de organizá-los e interpretá-los com o auxílio de gráficos. Esse objetivo foi atingido com sucesso, já que foi possível obter um conjunto de dados consistente, calcular medidas estatísticas importantes e tirar conclusões relevantes sobre o comportamento dos lançamentos.

 Durante a atividade, foi possível compreender melhor, na prática, conceitos como média, desvio padrão, variância e coeficiente de variação. Além disso, o experimento mostrou como pequenas mudanças nas condições iniciais podem influenciar os resultados, destacando a importância do controle experimental e da repetição das medições para garantir maior confiabilidade.

 Os dados obtidos apresentaram boa qualidade, com baixa variabilidade e distribuição relativamente uniforme, indicando consistência nos lançamentos. Mesmo com a presença de alguns valores atípicos, o conjunto se manteve estável, permitindo análises coerentes e confiáveis, dentro do esperado para esse tipo de experimento.

 Como melhorias, seria interessante utilizar instrumentos de medição mais precisos, aprimorar o controle das condições de lançamento (como força aplicada) e garantir uma superfície totalmente nivelada. Além disso, automatizar o disparo da catapulta poderia reduzir interferências humanas, aumentando a precisão e a repetibilidade dos resultados.

- O desenvolvimento deste projeto foi baseado no livro @Rbasico2022

## 📖 Referências